# Introduction {#intro}
## General Introduction
Marine fisheries in Tanzania are mainly artisanal and undertaken mostly from small, non-motorized fishing vessels such as dugout, outriggers, dhows, and boats [@jiddawi1997]. Only about 10% of fishing crafts are motorized. This constraint limits most of the fishing effort to inside the reef and rarely is fishing undertaken beyond territorial waters about 30 km offshore [@de2006review]. The most commonly used fishing gear is the artesian handline, longline, gillnet, traps, and sharknets [@mngulwi]. Despite the fact that artisanal fisheries use low technology, it lands more than 90% of the total marine fish [@semesi2001].

Catch are landed on fish landing sites (FLS)^[Fish landings are defined as the catches of marine fish landed in foreign or domestics ports. Marine capture fisheries landings are subject to changes in market demand and prices as well as the need to rebuild stocks to maximum sustainable yield levels in order to achieve long-term sustainable use of marine resources.], which in most cases are located in urban areas or in small fishing village along the coastline. The Food and Agriculture Organization of the United Nation (FAO) defined FLS as sea-land areas where fishermen land their daily catches for auctioning [@karin] and where fisheries related boats are anchored throughout the year [@medina]. FLS have different characteristics, largely determined by the nature of the fishing effort (type and number of vessels, gears and fishers), total catch (fish supply), population size (fish demand), landing facilities, accessibility, potable water and electrical supply among others [@karin]. 

Fish landing sites are not distributed randomly in time and space but tend to aggregate usually in response to particular physical feature of environment and fisheries abundance. Distribution of fish landing sites varies strongly in different scales from a few meters to many kilometers [@caddy]. @sobo reported that fish landing sites tend to be scattered on a certain geographical area and some of them were located in areas that are not easily accessible. It has been recognized that for the successful management of the artisanal fisheries, it is important to understand not only characteristic of the fish landing site, but also their spatial distribution patterns (like clustered, randomly or spatially dispersed) [@caddy] and investment value for proper management of the fisheries sector.

In Tanzania, fisheries frame surveys^[A Frame Survey is a census-based approach in which data is collected on all fishing vessels and gear (at all homeports/fishing sites), which could be potentially operating within the estimation context or stratum, ... They can also be used to provide information on the socio-economics and demography of fishing communities.] referred to as fisheries census are usually used to generate important information of fish landing sites required for management and planning purposes of artisanal fishery [@sobo]. Fisheries frame survey mainly focus to provide information on number of landing sites, fishers, number and types of fishing crafts and their mode of propulsion, number and types of gears, facilities at the fish landing sites including accessibility as well as service providers. However, the geographical coordinate’s points required for mapping and assessing the spatial distribution patterns of fish landing sites is not recorded during the survey. @ibengwe reported that mapping of more than 250 fish landing sites surveyed in 2007 could not be done because of the limited geographical coordinate. Therefore there is a need to integrate the spatial component of fish landing sites into the fisheries frame survey for the purposes of producing better information to support decision making and management plans of the fisheries sector. 

Mapping refers to representation of geographical position of fish landing sites of the earth’s surface on digital or paper map [@kraak]. Mapping fish landing site has several advantage such as it provides visualization^[The representation of an object, situation, or set of information as a chart or other image] of spatial distributions of both fish landing sites and their characteristics; illustrate social and economical activities [@carocci]. In addition, maps reveal critical location such as FLS known for high fish catch [@chapman]. Thus, mapping reveals very valuable information on unnoticed changes in space and time which may not be evident in Fisheries Frame Surveys Reports. Thus, this calls for strengthening of the interface between traditional method for assessing fisheries production factor (Fisheries Frame Survey) and modern technology that integrate the spatial geographical locations of FLS together with their associated characteristics (attribute information).

A Geographical Information System (GIS) is an ideal platform on which mapping the spatial distribution and characteristics of FLS become possible. A GIS is a computer-based tool for mapping and analysing events and places on the Earth’s surface. Mapping software like ArcMap allows display, query, update, and analysis of geographic locations of fish landing sites and the information linked to those locations. A GIS performs six tasks which include data input, data manipulation, data management, query and analysis, and finally visualization [@booth] as well as statistical analysis of the spatially georeferenced data [@breman]. In addition, GIS has the power not only to create maps, but also integrate different information and visualise scenarios, present ideas, and provide solutions for complicated problems [@kam].

Much of the "power of GIS" in resource management issues is based on its spatial analysis capabilities [@martin]. Spatial analysis refers to the ability of the analysis to manipulate spatial data into different forms and to extract additional meaning as a result [@kam]. It encompasses a variety of methods and procedures developed in different disciplines [@martin. A quantitatively-based framework for spatial analysis can be categorized into three broad classes visualization, exploratory data analysis and model building [@caddy]. These vary in complexity from simple map overlay operations to statistical models, such as primary productivity models [@fisher]. 

GIS is also a fundamental communication tool that can be used to promote interaction between science and various stages of the policy and decision-making cycle. GIS create static and interactive maps, which are the primary means for communicating spatial information of geographical feature like fish landing sites [@breman]. With its extensive graphic component, GIS created maps can reduce complexity and add value by summarizing, synthesizing and illustrating critical issues facing artisanal fisheries [@booth]. Hence provide information for better decision making with high level of confidence about where and which fish landing site need more management attention and how to allocate management resources [@caddy]. 

The scientific community involved in the study of fishery resources has recognized that approaches seeking to contribute to the development and management of living marine resources should be integrated, i.e., including the temporal and spatial dimensions of their variability [@kam]. As a consequence, creating maps of the fishery, fishing landing sites and production factor with which they interact, should be a priority task when planning fishing development and management plans [@caddy]. As it has been seen in other fields of science in which problems in relation to space do occur, the application of a new and promising tool, GIS, can be   translated in a remarkable improvement in spatial management of the fishery sector [@fisher2004], in particular when combined with other management methods such as fisheries frame survey. 

In Tanzania, the use of spatial information technology for the purposes of planning and management artisanal fisheries is yet to find its rightful place. Therefore this study present the use of GIS for mapping the spatial distribution, characteristic and investment value of fish landing site based on geo-referenced data collected during field visits and fisheries frame survey in Bagamoyo and Kinondoni Districts as case study. The characteristics and investment value of fish landing sites are critically discussed, and some recommendations presented.

##	Statement of the Problem
Despite having a database for FLS along the entire coastline of Tanzania mainland, the Fisheries Development Division has not been able to produce digital maps showing the spatial distribution of FLS. This is because the geospatial component required for making thematic maps of FLS is not part of the data recorded during Fish Frame Survey. Furthermore, information such as the value of production factors (equipments and/or facilities) of FLS is also not collected, hence the information of the wealth of the fish landing site is limited. Knowing where fish landing sites are geographically located and their investment value is essential information required to support better decision making processes for planning and management of artisanal fisheries in Tanzania. 

##	Research Objective
###	General Objective
This study generally seeks to bridge the gap that currently exists between mapping fish landing sites and fisheries frame surveys information, within the specific context of a small-scale artisanal fishery using Geographical Information System (GIS) technology. 

### Specific Objectives
The specific objectives are:-

1. To map the spatial distribution of fish landing sites along the coast of Kinondoni and Bagamoyo districts
2. To characterize fish landing sites along the coast of Kinondoni and Bagamoyo districts
3. To determine the investment value of the fish landing sites found within the coast of Kinondoni and Bagamoyo districts

## Significance of the Study
The overall target of the study is to contribute to the science and knowledge on the use of GIS technology for spatial planning and management of coastal and marine resources, including artisanal fisheries. The findings of this study provide spatial information on spatial distribution (location), investment value and factors influencing FLS along coast of Kinondoni and Bagamoyo district, which can be used to support policy and decision making for improved management and development of the artisanal fisheries sector. The study has also established GIS-based database (spatial database) for fish landing sites found at Bagamoyo and Kinondoni Districts, which will serve as a model for efficient and effective organization, update, and query of spatially georeferenced data of fish landing sites and facilitate analysis of geospatial information. Furthermore, this study serves as a baseline of using a GIS technology as management tool to facilitate easy and timely access of the required information in the right format by different end users, including policy and decision makers, fisheries resource managers, fishers, scientists and the private sector.
 