--- 
title: "Putting Fishing Landing Sites and their Insfrastructure on Spatial Aspect"
author: "Masumbuko Semba"
date: "updated on `r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [master.bib]
biblio-style: elsevier.csl
link-citations: yes
description: "This dissertation is copyright material protected under the Berne Convention, the Copyright Act 1999 and other international and national enactments, in that behalf, on intellectual property. It may not be reproduced by any means, in full or in part, except for short extracts in fair dealings, for research or private study, critical scholarly review or discourse with an acknowledgement, without the written permission of the Directorate of Postgraduate Studies, on behalf of both the author and the University of Dar es Salaam"
---

# Aknowledgement {-}
I owe many thanks to people who helped and supported me throughout the dissertation. First, my deepest thanks goes to my Supervisor Dr. Christopher Muhando of the Institute of Marine Sciences (IMS) for guiding and correcting various documents with attention and care. He has taken pains to go through the Dissertation and made necessary correction as needed. I am deeply grateful to Dr. Magreth Kywelyanga, Director of the Institute of Marine Sciences for providing me an opportunity to study at the Institute. I wish to express my thanks to the Western Indian Ocean Marine Science Association (WIOMSA) for financial support and guidance. Sincere appreciation goes to the Fisheries Development Division for allowing me to use fish landing site data from the Fisheries Frame Survey Database. Special thanks go to Ms. Lilian Omolo and Mr. Edward Kimakwa for editing and proofing various drafts of my work. I would like to appreciate Ms. Bupe Mwapamba, Mr. Sijali Juma and Mr. Magege, fisheries officers at Bagamoyo and Kinondoni Districts for their kind co-operation that contributed to the completion of my project work. I would also thank my Institution members without whom this research would have been a distant reality. Finally, I extend my heartfelt thanks, gratitude and love to my friends and my beloved parents for their support, strength, and help.

# Abstract {-}
Mapping artisanal fisheries activities for Bagamoyo and Kinondoni Districts based on  spatial patterns of landing sites was carried out in a Geographic Information System (GIS) environment. Spatial attributes of the fish landing sites from fisheries frame survey database and field collected data was analyzed. The spatial distribution of the fish landing sites was weighted using Average Nearest Neighbor Tool (ANNT). The ANNT revealed that fish landing sites were not scattered but statistically spatially dispersed (P<0.01) in the study area, and the hierarchy for the relative importance of the landing sites in the area was established. Msasani, Kunduchi and Custom were the most prominent ones. Moran I tool (MIT) showed a significantly high number of fishing vessels for fish landing sites at Kinondoni District (P<0.01). Analysis of the value of fish landing sites based on the price of fishing vessels showed that Kunduchi had the highest investment value (532.65 Tsh Million), and was dominated by expensive fishing vessels (Boats), which constituted more than 52% of its total fishing vessel. Kunduchi was followed by Mlingotini (256.9 Tsh Million), and Msasani (152.05 Tsh Million), Nchipana(128.8 Tsh Million) and Custom (121.2 Tsh Million). It is important to highlight that price value of fishing vessels come from in situ data, while the number of fishing vessels come from fisheries frame survey database. Although, the number of fisheries records used for only ten fish landing sites, the study attempts to provide new insight on the spatial distribution, characteristic and investment value of landing sites, however, further studies will be needed to cover the whole coastline.  
